// File generated by FlutterFire CLI.
// This is a placeholder configuration file.
// Replace with your actual Firebase configuration by running:
// flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // PLACEHOLDER - Replace with your actual Firebase config
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForBuildOnly-ReplaceWithRealKey',
    appId: '1:123456789:web:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'expenwall-demo',
    authDomain: 'expenwall-demo.firebaseapp.com',
    storageBucket: 'expenwall-demo.appspot.com',
    measurementId: 'G-MEASUREMENT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForBuildOnly-ReplaceWithRealKey',
    appId: '1:123456789:android:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'expenwall-demo',
    authDomain: 'expenwall-demo.firebaseapp.com',
    databaseURL: 'https://expenwall-demo.firebaseio.com',
    storageBucket: 'expenwall-demo.appspot.com',
    measurementId: 'G-MEASUREMENT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForBuildOnly-ReplaceWithRealKey',
    appId: '1:123456789:ios:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'expenwall-demo',
    authDomain: 'expenwall-demo.firebaseapp.com',
    storageBucket: 'expenwall-demo.appspot.com',
    measurementId: 'G-MEASUREMENT',
    iosClientId: '123456789-abc123.apps.googleusercontent.com',
    iosBundleId: 'com.expenwall.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForBuildOnly-ReplaceWithRealKey',
    appId: '1:123456789:ios:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'expenwall-demo',
    authDomain: 'expenwall-demo.firebaseapp.com',
    storageBucket: 'expenwall-demo.appspot.com',
    measurementId: 'G-MEASUREMENT',
    iosClientId: '123456789-abc123.apps.googleusercontent.com',
    iosBundleId: 'com.expenwall.mobile',
  );
}
